### ISSUE TITLE
after submitting the email; relation "django_rest_passwordreset_resetpasswordtoken" does not exist

### ISSUE THREAD

**Issue by noorarahili** [anx-ckreuzberger/django-rest-passwordreset#57]
Hi all,
I'm testing this locally, and when I submit the email, it gives me an error. this is the output:

```
Internal Server Error: /api/password_reset/

Traceback (most recent call last):
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "django_rest_passwordreset_resetpasswordtoken" does not exist
LINE 1: DELETE FROM "django_rest_passwordreset_resetpasswordtoken" W...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django_rest_passwordreset/views.py", line 105, in post
    clear_expired(now_minus_expiry_time)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django_rest_passwordreset/models.py", line 94, in clear_expired
    ResetPasswordToken.objects.filter(created_at__lte=expiry_time).delete()
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/db/models/query.py", line 617, in delete
    deleted, _rows_count = collector.delete()
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/db/models/deletion.py", line 284, in delete
    count = qs._raw_delete(using=self.using)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/db/models/query.py", line 631, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 80, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 884, in execute_sql
    cursor.execute(sql, params)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/debug_toolbar/panels/sql/tracking.py", line 164, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/debug_toolbar/panels/sql/tracking.py", line 106, in _record
    return method(sql, params)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/noora/cartwheel_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_rest_passwordreset_resetpasswordtoken" does not exist
LINE 1: DELETE FROM "django_rest_passwordreset_resetpasswordtoken" W...
                    ^

[31/Jul/2019 14:01:19] "POST /api/password_reset/ HTTP/1.1" 500 200689
```

can you help me PLZ

**Comment by anx-ckreuzberger** [comment]
You probably did not run `python manage.py migrate` (I just saw that this is missing from the installation instructions).

**Comment by noorarahili** [comment]
I did run migration command. but it is still the same

**Comment by anx-ckreuzberger** [comment]
```
psycopg2.ProgrammingError: relation "django_rest_passwordreset_resetpasswordtoken" does not exist
LINE 1: DELETE FROM "django_rest_passwordreset_resetpasswordtoken" W...
```

This error is saying that the table `django_rest_passwordreset_resetpasswordtoken` does not exist. This table should have been created by running migrations. Did you add `'django_rest_passwordreset',` to your `INSTALLED_APPS` in settings.py, as detailed in the [README](https://github.com/anx-ckreuzberger/django-rest-passwordreset#quickstart)?

**Comment by noorarahili** [comment]
yes, I did all what is written on setting up on the README

**Comment by anx-ckreuzberger** [comment]
I'm sorry, but the error suggests that something is wrong with django migrations or that there is an inconsistent state within your database, but not within the library.

**Comment by yusufselimkaratas** [comment]
Hi, How did you solve that?
