### ISSUE TITLE
MySQL - Incorrect table definition

### ISSUE THREAD

**Issue by lmantesbtm** [anx-ckreuzberger/django-rest-passwordreset#9]
Hi, there is an issue regarding the migration of django_rest_passwordreset.0002_pk_migration,

Here is the stacktrace:
Traceback (most recent call last):
  File ".local/share/virtualenvs/BTM_KYC-GCftzs5x/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File ".local/share/virtualenvs/BTM_KYC-GCftzs5x/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File ".local/share/virtualenvs/BTM_KYC-GCftzs5x/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File ".local/share/virtualenvs/BTM_KYC-GCftzs5x/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File ".local/share/virtualenvs/BTM_KYC-GCftzs5x/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File ".local/share/virtualenvs/BTM_KYC-GCftzs5x/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File ".local/share/virtualenvs/BTM_KYC-GCftzs5x/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File ".local/share/virtualenvs/BTM_KYC-GCftzs5x/lib/python3.5/site-packages/MySQLdb/connections.py", line 278, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1075, 'Incorrect table definition; there can be only one auto column and it must be defined as a key')

This SQL query is causing this.
b'ALTER TABLE `django_rest_passwordreset_resetpasswordtoken` MODIFY `id` integer AUTO_INCREMENTNULL'

Error:
_mysql_exceptions.OperationalError: (1075, 'Incorrect table definition; there can be only one auto column and it must be defined as a key')

I have printed the query to know which one is causing this issue.

I don't know if this is just in my machine but kindly look into this.

Thanks.

**Comment by anx-ckreuzberger** [comment]
Thanks for the information. Seems to be related to issue #8.

**Comment by anx-ckreuzberger** [comment]
I've released version 0.9.6 of this package which should resolve issue #8. Can you have a look if this version also fixes your problem?

**Comment by lmantesbtm** [comment]
Thanks. I will check it.

**Comment by lmantesbtm** [comment]
Its working fine now. Thank you.

Closing issue.

**Comment by nikksbagul** [comment]
Getting same issue with Django 2.0 and django-rest-passwordreset==0.9.7

  Applying django_rest_passwordreset.0001_initial... OK
  Applying django_rest_passwordreset.0002_pk_migration...Traceback (most recent call last):
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1075, 'Incorrect table definition; there can be only one auto column and it must be defined as a key')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 216, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 509, in alter_field
    old_db_params, new_db_params, strict)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 650, in _alter_field
    params,
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 117, in execute
    cursor.execute(sql, params)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/virtualenv/zoop_credit/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1075, 'Incorrect table definition; there can be only one auto column and it must be defined as a key')
